
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ggraph"
version = "0.0.1"
description = "Python interface engine and graph definition language for GGUF-based models."
authors = [
    { name = "Alex O'Connell", email = "git@alexoconnell.net" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=2.2.6",
    "tokenizers>=0.21.1",
    "jinja2>=3.1.6",
    "lark>=1.2.2",
    "matplotlib",
    "gguf>=0.17.0",
]

[project.optional-dependencies]
gen = [
    "ctypeslib2 @ git+https://github.com/acon96/ctypeslib-ggml.git",
    "clang==14"
]

[project.urls]
Homepage = "https://github.com/acon96/ggraph.py"
Repository = "https://github.com/acon96/ggraph.py"

[tool.setuptools.packages.find]
where = ["."]
include = ["ggraph*"]

[tool.setuptools.package-data]
ggraph = ["*.ggml"]

[project.scripts]
ggraph-cli = "ggraph.cli:main"