
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ggraph"
version = "0.1.0"
description = "Python interface and utilities for GGML-based model inference, with support for custom model graphs and backends."
authors = [
    { name = "Alex O'Connell", email = "git@alexoconnell.net" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "transformers",
    "lark",
    "matplotlib"
]

[project.urls]
Homepage = "https://github.com/acon96/ggraph.py"
Repository = "https://github.com/acon96/ggraph.py"

[tool.setuptools]
packages = ["gglm"]

[project.scripts]
"ggraph.py" = "gglm.ggraph:main"